/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

/**
 * TypeScript definitions for the Headless Admin User REST API (version v1.0).
 *
 * @generated by the @liferay/frontend-js-rest-client-generator type generator from
 * headless-admin-user-impl/rest-openapi.yaml. Do not edit by hand.
 */

export const BASE_PATH = "/o/headless-admin-user/v1.0";

// Envelope & Liferay extension types

/** Paginated collection envelope returned for list (array) endpoints. */
export interface Page<T> {
	actions?: Record<string, Record<string, string>>;
	facets?: unknown[];
	items: T[];
	lastPage: number;
	page: number;
	pageSize: number;
	totalCount: number;
}

/** Liferay expando/custom field (not formally defined in the OpenAPI schema). */
export interface CustomField {
	customValue?: {data?: unknown};
	dataType?: string;
	fieldType?: string;
	label?: string;
	name?: string;
	nestedFields?: Record<string, unknown>;
}

/** Liferay permission entry (not formally defined in the OpenAPI schema). */
export interface Permission {
	actionIds?: string[];
	roleName?: string;
}

// DTOs (components.schemas)

/** An account represents an external account, for example a customer business. */
export interface Account {
	/** The account's contact information. */
	accountContactInformation?: {
		/** A list of the account's email addresses, with one optionally marked as primary. */
		emailAddresses?: EmailAddress[];
		/** The account's Facebook account. */
		facebook?: string;
		/** The ID of the `contactInformation`. — read-only */
		id?: number;
		/** The account's Jabber handle. */
		jabber?: string;
		/** A list of account's postal addresses, with one optionally marked as primary. */
		postalAddresses?: PostalAddress[];
		/** The account's Skype handle. */
		skype?: string;
		/** The account's SMS number. */
		sms?: string;
		/** A list of the account's phone numbers, with one optionally marked as primary. */
		telephones?: Phone[];
		/** The account's Twitter handle. */
		twitter?: string;
		/** A list of the account's web URLs, with one optionally marked as primary. */
		webUrls?: WebUrl[];
	};
	/** A list of the account's account groups. — read-only */
	accountGroupBriefs?: AccountGroupBrief[];
	/** A list of the account's roles. — read-only */
	accountRoles?: AccountRole[];
	/** The users linked to the account */
	accountUserAccounts?: UserAccount[];
	/** Block of actions allowed by the user making the request. — read-only */
	actions?: Record<string, Record<string, string>>;
	/** The user who created the account. — read-only */
	creator?: Creator;
	customFields?: CustomField[];
	/** The account's creation date. — read-only */
	dateCreated?: string;
	/** The account's most recent modification date. — read-only */
	dateModified?: string;
	defaultBillingAddressExternalReferenceCode?: string;
	defaultBillingAddressId?: number;
	defaultShippingAddressExternalReferenceCode?: string;
	defaultShippingAddressId?: number;
	description?: string;
	/** The account's email domains. Users assigned to this account generally will have email addresses under one of these domains. */
	domains?: string[];
	/** The optional external key of this account. */
	externalReferenceCode?: string;
	/** read-only */
	id?: number;
	/** A list of keywords describing the account. */
	keywords?: string[];
	logoBase64?: string;
	logoExternalReferenceCode?: string;
	logoId?: number;
	logoURL?: string;
	name?: string;
	/** The number of this account's associated users. — read-only */
	numberOfUsers?: number;
	organizationExternalReferenceCodes?: string[];
	organizationIds?: number[];
	parentAccountExternalReferenceCode?: string;
	parentAccountId?: number;
	permissions?: Permission[];
	/** The addresses linked to the account */
	postalAddresses?: PostalAddress[];
	status?: number;
	taxId?: string;
	/** The categories associated with this account. — read-only */
	taxonomyCategoryBriefs?: TaxonomyCategoryBrief[];
	type?: "business" | "guest" | "person" | "supplier";
}

/** Represents an account's basic information, to be embedded in other resources. This resource's ID can be used to query the account's complete information. */
export interface AccountBrief {
	/** The account's external reference code. */
	externalReferenceCode?: string;
	/** The account's ID. — read-only */
	id?: number;
	/** The account's name. */
	name?: string;
	/** A list of the user's roles. — read-only */
	roleBriefs?: RoleBrief[];
	/** The account's type. */
	type?: string;
}

export interface AccountGroup {
	/** The list of accounts associated with this account group. */
	accountBriefs?: AccountBrief[];
	/** Block of actions allowed by the user making the request. — read-only */
	actions?: Record<string, Record<string, string>>;
	/** The user who created the account group. — read-only */
	creator?: Creator;
	customFields?: CustomField[];
	/** The account group's creation date. — read-only */
	dateCreated?: string;
	/** The account group's most recent modification date. — read-only */
	dateModified?: string;
	description?: string;
	externalReferenceCode?: string;
	/** read-only */
	id?: number;
	name?: string;
	permissions?: Permission[];
}

export interface AccountGroupBrief {
	externalReferenceCode?: string;
	/** read-only */
	id?: number;
	name?: string;
}

/** A role that belongs to an account */
export interface AccountRole {
	/** The primary key of the account that owns this role. — read-only */
	accountId?: number;
	description?: string;
	displayName?: string;
	/** The optional external key of this account role. */
	externalReferenceCode?: string;
	/** read-only */
	id?: number;
	name?: string;
	/** The primary key of the underlying system role. — read-only */
	roleId?: number;
	/** The role's type. — read-only */
	roleType?: number;
}

export interface AssetLibraryBrief {
	/** The asset library's external reference code. */
	externalReferenceCode?: string;
	/** The asset library's group ID. — read-only */
	groupId?: number;
	/** The asset library's name. — read-only */
	name?: string;
}

/** Represents the user who created/authored the content. Properties follow the [creator](https://schema.org/creator) specification. */
export interface Creator {
	/** The user's additional name, which can be used as a middle name. — read-only */
	additionalName?: string;
	/** The type of the content. — read-only */
	contentType?: string;
	/** The user's external reference code. — read-only */
	externalReferenceCode?: string;
	/** The user's surname (last name). — read-only */
	familyName?: string;
	/** The user's first name. — read-only */
	givenName?: string;
	/** The user's ID. — read-only */
	id?: number;
	/** A relative URL to the user's profile image. — read-only */
	image?: string;
	/** The user's full name. — read-only */
	name?: string;
	/** A relative URL to the user's profile. — read-only */
	profileURL?: string;
}

/** Represents an email address. Properties follow the [email](https://schema.org/email) specification. */
export interface EmailAddress {
	/** The email address. */
	emailAddress?: string;
	/** The email address's external reference code. */
	externalReferenceCode?: string;
	/** The email address's ID. */
	id?: number;
	/** A flag that indicates whether this is the main email address of the user/organization. */
	primary?: boolean;
	/** The email address's type. */
	type?: string;
}

export interface FileEntry {
	externalReferenceCode?: string;
	id?: number;
	/** read-only */
	link?: Link;
	name?: string;
	/** read-only */
	previewURL?: string;
	/** read-only */
	thumbnailURL?: string;
}

export interface Image {
	image?: string;
}

export interface Link {
	href?: string;
	label?: string;
}

/** Represents an organization. Organizations can contain other organizations (suborganizations). Properties follow the [Organization](https://schema.org/Organization) specification. */
export interface Organization {
	/** The list of accounts associated with this organization. — read-only */
	accountBriefs?: AccountBrief[];
	/** read-only */
	actions?: Record<string, Record<string, string>>;
	childOrganizations?: Organization[];
	/** The text of a comment associated with the organization. */
	comment?: string;
	/** The user who created the organization. — read-only */
	creator?: Creator;
	customFields?: CustomField[];
	/** The organization's creation date. — read-only */
	dateCreated?: string;
	/** The most recent time any of the organization's fields changed. — read-only */
	dateModified?: string;
	/** The optional external key of this organization. */
	externalReferenceCode?: string;
	/** The organization's ID. */
	id?: string;
	/** A relative URL to the organization's image. — read-only */
	image?: string;
	imageBase64?: string;
	/** The organization's image external reference code. */
	imageExternalReferenceCode?: string;
	/** The organization's image id. */
	imageId?: number;
	/** A list of keywords describing the organization. */
	keywords?: string[];
	/** The organization's postal information (country and region). */
	location?: {
		/** The organization's country. This follows the [`addressCountry`](https://schema.org/addressCountry) specification. */
		addressCountry?: string;
		/** The organization's country isocode. — read-only */
		addressCountryCode?: string;
		/** The organization's country external reference code. */
		addressCountryExternalReferenceCode?: string;
		addressCountry_i18n?: Record<string, string>;
		/** The organization's region. This follows the [`addressRegion`](https://schema.org/addressRegion) specification. */
		addressRegion?: string;
		/** The organization's region code. — read-only */
		addressRegionCode?: string;
		/** The organization's region external reference code. */
		addressRegionExternalReferenceCode?: string;
		/** The location's ID. — read-only */
		id?: number;
	};
	/** The organization's name. */
	name?: string;
	/** The number of this organization's associated accounts. — read-only */
	numberOfAccounts?: number;
	/** The number of this organization's child organizations. — read-only */
	numberOfOrganizations?: number;
	/** The number of this organization's associated users. — read-only */
	numberOfUsers?: number;
	organizationAccounts?: Account[];
	/** The organization's contact information, which includes email addresses, postal addresses, phone numbers, and web URLs. This is modeled internally as a `Contact`. */
	organizationContactInformation?: {
		/** The organization's email addresses, with one optionally marked as primary. */
		emailAddresses?: EmailAddress[];
		/** The organization's postal addresses, with one optionally marked as primary. */
		postalAddresses?: PostalAddress[];
		/** The organization's phones numbers, with one optionally marked as primary. */
		telephones?: Phone[];
		/** The organization's web URLs, with one optionally marked as primary. */
		webUrls?: WebUrl[];
	};
	/** The organization's parent organization. */
	parentOrganization?: Organization;
	permissions?: Permission[];
	/** The list of roles associated with this organization. — read-only */
	roleBriefs?: RoleBrief[];
	/** A list of services the organization provides. This follows the [`Service`](https://www.schema.org/Service) specification. */
	services?: ({
		/** A list of hours when the organization is open. This follows the [`OpeningHoursSpecification`](https://www.schema.org/OpeningHoursSpecification) specification. */
		hoursAvailable?: ({
			/** The organization's closing time (in `HH:MM` format). */
			closes?: string;
			/** The day of the week. */
			dayOfWeek?: string;
			/** The organization's opening time (in `HH:MM` format). */
			opens?: string;
		})[];
		/** The type of service the organization provides. */
		serviceType?: string;
	})[];
	/** The categories associated with this organization. — read-only */
	taxonomyCategoryBriefs?: TaxonomyCategoryBrief[];
	/** The tree path of the organization. */
	treePath?: string;
	/** The list of users associated with this organization. — read-only */
	userAccountBriefs?: UserAccountBrief[];
	userAccounts?: UserAccount[];
}

/** Represents an organization's basic information, to be embedded in other resources. This resource's ID can be used to query the organization's complete information. */
export interface OrganizationBrief {
	/** The organization's external reference code. — read-only */
	externalReferenceCode?: string;
	/** The organization's ID. — read-only */
	id?: number;
	/** The organization's name. — read-only */
	name?: string;
	/** A list of the user's roles. — read-only */
	roleBriefs?: RoleBrief[];
}

/** Represents a phone number. This follows the [telephone](https://schema.org/telephone) specification. */
export interface Phone {
	/** The phone number's extension. */
	extension?: string;
	/** The phone number's external reference code. */
	externalReferenceCode?: string;
	/** The phone number's ID. */
	id?: number;
	/** The phone number without its extension. */
	phoneNumber?: string;
	/** The phone number's type. */
	phoneType?: string;
	/** A flag that identifies whether this is the main phone number of the user/organization. */
	primary?: boolean;
}

/** Represents a mailing address. This follows the [`PostalAddress`](https://www.schema.org/PostalAddress) specification. */
export interface PostalAddress {
	/** The address's country (e.g., USA). */
	addressCountry?: string;
	/** The address' country external reference code. */
	addressCountryExternalReferenceCode?: string;
	addressCountry_i18n?: Record<string, string>;
	/** The address's locality (e.g., city). */
	addressLocality?: string;
	/** The address's region (e.g., state). */
	addressRegion?: string;
	/** The address' region external reference code. */
	addressRegionExternalReferenceCode?: string;
	/** The address's subtype. */
	addressSubtype?: string;
	/** The address's type. */
	addressType?: string;
	/** The optional external key of this address. */
	externalReferenceCode?: string;
	/** The address's ID. */
	id?: number;
	/** The address's name. */
	name?: string;
	/** The phone number. */
	phoneNumber?: string;
	/** The address's postal code (e.g., zip code). */
	postalCode?: string;
	/** A flag that identifies whether this is the main address of the user/organization. */
	primary?: boolean;
	/** The street address's first line (e.g., 1600 Amphitheatre Pkwy.). */
	streetAddressLine1?: string;
	/** The street address's second line. */
	streetAddressLine2?: string;
	/** The street address's third line. */
	streetAddressLine3?: string;
}

/** Represents a relationship between a user and a company or site. This follows the [`Role`](https://www.schema.org/Role) specification. */
export interface Role {
	/** Block of actions that the user can perform with the roles. — read-only */
	actions?: Record<string, Record<string, string>>;
	/** A list of languages for which the role has a translation. — read-only */
	availableLanguages?: string[];
	/** The role's creator. — read-only */
	creator?: Creator;
	/** The role's creation date. — read-only */
	dateCreated?: string;
	/** The last time any of the role's fields were changed. — read-only */
	dateModified?: string;
	/** The role's description. */
	description?: string;
	description_i18n?: Record<string, string>;
	/** The optional external key of this role. */
	externalReferenceCode?: string;
	/** The role's ID. — read-only */
	id?: number;
	/** The role's name. */
	name?: string;
	name_i18n?: Record<string, string>;
	permissions?: Permission[];
	rolePermissions?: RolePermission[];
	/** The role's type. */
	roleType?: string;
	/** The role's subtype. */
	subtype?: string;
}

/** Represents a role's basic information, to be embedded with other resources. The ID of this resource can be used to query the role's complete information. */
export interface RoleBrief {
	/** The role's external reference code. */
	externalReferenceCode?: string;
	/** The role's ID. — read-only */
	id?: number;
	/** The role's key. */
	key?: string;
	/** The role's name. */
	name?: string;
	/** read-only */
	name_i18n?: Record<string, string>;
	/** The role's type. */
	roleType?: number;
}

export interface RolePermission {
	actionIds?: string[];
	id?: number;
	label?: string;
	primaryKey?: string;
	resourceName?: string;
	roleId?: number;
	scope?: number;
}

/** Represents a set of users that meet certain criteria. Segments may be used to create customized experiences for users. */
export interface Segment {
	/** A flag that indicates whether the segment is active. — read-only */
	active?: boolean;
	/** The segment's criteria. — read-only */
	criteria: string;
	/** The segment's criteria in JSON. — read-only */
	criteriaValue?: Record<string, Record<string, unknown>>;
	/** The segment's creation date. — read-only */
	dateCreated?: string;
	/** The segment's most recent modification date. — read-only */
	dateModified?: string;
	/** The segment's ID. — read-only */
	id?: number;
	/** The segment's name. — read-only */
	name: string;
	/** The ID of the segment's site. — read-only */
	siteId?: number;
	/** The segment's source. — read-only */
	source?: string;
}

/** Represents a user who belongs to a segment. */
export interface SegmentUser {
	/** The user's email address. — read-only */
	emailAddress?: string;
	/** The user's ID. — read-only */
	id?: number;
	/** The user's full name. — read-only */
	name?: string;
}

/** Represents a shared asset. */
export interface SharedAsset {
	/** The shared asset actions. — read-only */
	actionIds?: string[];
	/** Block of actions allowed by the user making the request. — read-only */
	actions?: Record<string, Record<string, string>>;
	/** The shared asset type. — read-only */
	assetType?: string;
	/** read-only */
	className?: string;
	/** read-only */
	classPK?: number;
	/** The shared asset creator. — read-only */
	creator?: Creator;
	/** The shared asset creation date. — read-only */
	dateCreated?: string;
	/** The shared asset modified date. — read-only */
	dateModified?: string;
	/** The shared asset external reference code. — read-only */
	externalReferenceCode?: string;
	/** Optional field with the embedded file, can be embedded with nestedFields — read-only */
	file?: FileEntry;
	/** The shared asset file type icon. — read-only */
	fileTypeIcon?: string;
	/** The shared asset file type icon color. — read-only */
	fileTypeIconColor?: string;
	/** The shared asset ID. — read-only */
	id?: number;
	/** Whether the shared asset is shareable or not — read-only */
	shareable?: boolean;
	/** The name of the site to which this shared asset is scoped. — read-only */
	siteName?: string;
	/** The shared asset title. — read-only */
	title?: string;
	/** If the shared asset is visible or not. */
	visible?: boolean;
}

/** Represents the site where the content is created. Properties follow the [WebSite](https://schema.org/WebSite) specification. */
export interface Site {
	availableLanguages?: string[];
	creator?: Creator;
	description?: string;
	description_i18n?: Record<string, string>;
	descriptiveName?: string;
	descriptiveName_i18n?: Record<string, string>;
	friendlyUrlPath?: string;
	id?: number;
	key?: string;
	membershipType?: string;
	name?: string;
	name_i18n?: Record<string, string>;
	parentSiteId?: number;
	sites?: Site[];
}

/** Represents a site's basic information. */
export interface SiteBrief {
	/** The site's descriptive name. — read-only */
	descriptiveName?: string;
	/** read-only */
	descriptiveName_i18n?: Record<string, string>;
	/** The site's external reference code. — read-only */
	externalReferenceCode?: string;
	/** The site's ID. — read-only */
	id?: number;
	/** The site's name. — read-only */
	name?: string;
	/** read-only */
	name_i18n?: Record<string, string>;
	/** A list of the user's roles. — read-only */
	roleBriefs?: RoleBrief[];
}

export interface Subscription {
	contentId?: Record<string, unknown>;
	contentType?: string;
	/** read-only */
	dateCreated?: string;
	/** read-only */
	dateModified?: string;
	frequency?: string;
	/** read-only */
	id?: number;
	siteId?: number;
}

export interface TaxonomyCategoryBrief {
	/** Optional field with the embedded taxonomy category, can be embedded with nestedFields — read-only */
	embeddedTaxonomyCategory?: Record<string, unknown>;
	parentTaxonomyCategoryExternalReferenceCode?: string;
	parentVocabularyExternalReferenceCode?: string;
	/** The category's ID. — read-only */
	taxonomyCategoryId?: number;
	/** The category's name. — read-only */
	taxonomyCategoryName?: string;
	/** The localized category's names. — read-only */
	taxonomyCategoryName_i18n?: Record<string, string>;
	/** A unique reference to a taxonomy category. */
	taxonomyCategoryReference?: {
		/** The taxonomy category's external reference code. */
		externalReferenceCode?: string;
		/** The key of the site or asset library where the taxonomy category is located. */
		siteKey?: string;
	};
}

export interface Ticket {
	/** read-only */
	expirationDate?: string;
	/** read-only */
	extraInfo?: string;
	/** read-only */
	id?: number;
	/** read-only */
	key?: string;
}

/** Represents a user. */
export interface UserAccount {
	/** A list of the user's account. — read-only */
	accountBriefs?: AccountBrief[];
	/** read-only */
	actions?: Record<string, Record<string, string>>;
	/** The user's additional name (e.g., middle name). */
	additionalName?: string;
	/** The user's alias or screen name. */
	alternateName?: string;
	/** The user's asset libraries. — read-only */
	assetLibraryBriefs?: AssetLibraryBrief[];
	/** The user's date of birth. */
	birthDate?: string;
	/** The user who created this user account. — read-only */
	creator?: Creator;
	/** The user's current password. Used to authenticate a user when they attempt to update their own password. — write-only */
	currentPassword?: string;
	customFields?: CustomField[];
	/** A relative URL to the user's dashboard. — read-only */
	dashboardURL?: string;
	/** The creation date of the user's account. — read-only */
	dateCreated?: string;
	/** The last time any field of the user's account was changed. — read-only */
	dateModified?: string;
	/** The user's main email address. */
	emailAddress?: string;
	/** The optional external key of this user account. */
	externalReferenceCode?: string;
	/** The user's surname (last name). */
	familyName?: string;
	/** The user's gender. */
	gender?: "Male" | "Female";
	/** The user's first name. */
	givenName?: string;
	/** A flag that indicates whether the user has been signed in. — read-only */
	hasLoginDate?: boolean;
	/** The user's title (e.g., Dr., Mr., Mrs, Ms., etc.). */
	honorificPrefix?: string;
	/** The user's suffix (e.g., II, Jr., PhD, etc.). */
	honorificSuffix?: string;
	/** The user's ID. */
	id?: number;
	/** A relative URL to the user's profile image. — read-only */
	image?: string;
	/** The user's profile image external reference code. */
	imageExternalReferenceCode?: string;
	/** The user's profile image id. */
	imageId?: number;
	/** The user's job title. */
	jobTitle?: string;
	/** A list of keywords describing the user. — read-only */
	keywords?: string[];
	/** The user's preferred language. — read-only */
	languageDisplayName?: string;
	/** The user's preferred language id. */
	languageId?: string;
	/** The last time the user logged in. — read-only */
	lastLoginDate?: string;
	/** read-only */
	loginDate?: string;
	/** The user's full name. — read-only */
	name?: string;
	/** A list of the user's organizations. — read-only */
	organizationBriefs?: OrganizationBrief[];
	/** The user's password. — write-only */
	password?: string;
	permissions?: Permission[];
	/** A relative URL to the user's profile. — read-only */
	profileURL?: string;
	/** A list of the user's roles. — read-only */
	roleBriefs?: RoleBrief[];
	/** A list of the user's sites. — read-only */
	siteBriefs?: SiteBrief[];
	/** The user's status. */
	status?: "Active" | "Inactive";
	/** The categories associated with this user. — read-only */
	taxonomyCategoryBriefs?: TaxonomyCategoryBrief[];
	/** The user's contact information. */
	userAccountContactInformation?: {
		/** A list of the user's email addresses, with one optionally marked as primary. */
		emailAddresses?: EmailAddress[];
		/** The user's Facebook account. */
		facebook?: string;
		/** The ID of the `contactInformation`. — read-only */
		id?: number;
		/** The user's Jabber handle. */
		jabber?: string;
		/** A list of user's postal addresses, with one optionally marked as primary. */
		postalAddresses?: PostalAddress[];
		/** The user's Skype handle. */
		skype?: string;
		/** The user's SMS number. */
		sms?: string;
		/** A list of the user's phone numbers, with one optionally marked as primary. */
		telephones?: Phone[];
		/** The user's Twitter handle. */
		twitter?: string;
		/** A list of the user's web URLs, with one optionally marked as primary. */
		webUrls?: WebUrl[];
	};
	/** A list of the user's userGroups. — read-only */
	userGroupBriefs?: UserGroupBrief[];
}

/** Represents a user's basic information, to be embedded in other resources like UserGroup. */
export interface UserAccountBrief {
	/** The user's alias or screen name. */
	alternateName?: string;
	/** The user's main email address. */
	emailAddress?: string;
	/** The optional external key of this user account. */
	externalReferenceCode?: string;
	/** The user's ID. */
	id?: number;
	/** The user's full name. — read-only */
	name?: string;
}

/** Represents the definition of the user full name. */
export interface UserAccountFullNameDefinition {
	/** A list of the user's account. — read-only */
	userAccountFullNameDefinitionFields?: UserAccountFullNameDefinitionField[];
}

/** Represents the definition of a single part of the user full name. */
export interface UserAccountFullNameDefinitionField {
	/** read-only */
	key?: string;
	/** read-only */
	required?: boolean;
	/** read-only */
	values?: string[];
}

export interface UserGroup {
	/** read-only */
	actions?: Record<string, Record<string, string>>;
	/** The user who created the user group. — read-only */
	creator?: Creator;
	/** The user group's creation date. — read-only */
	dateCreated?: string;
	/** The user group's most recent modification date. — read-only */
	dateModified?: string;
	description?: string;
	externalReferenceCode?: string;
	/** read-only */
	id?: number;
	name?: string;
	permissions?: Permission[];
	/** The list of roles associated with this user group. — read-only */
	roleBriefs?: RoleBrief[];
	/** The list of users associated with this user group. — read-only */
	userAccountBriefs?: UserAccountBrief[];
	/** read-only */
	usersCount?: number;
}

/** Represents a UserGroup's basic information. */
export interface UserGroupBrief {
	description?: string;
	/** The user group's external reference code. — read-only */
	externalReferenceCode?: string;
	/** read-only */
	id?: number;
	name?: string;
}

/** Represents a URL to an external site. This is modeled internally as a `WebSite`. */
export interface WebUrl {
	/** The optional external key of this URL. */
	externalReferenceCode?: string;
	/** The URL's ID. */
	id?: number;
	/** A flag that identifies whether this is the main web address of the user/organization. */
	primary?: boolean;
	/** The absolute URL. */
	url?: string;
	/** The URL's type. */
	urlType?: string;
}

// Endpoints — keyed by `METHOD <path>` (prefix paths with BASE_PATH).

export interface Endpoints {
	/** Retrieves the account groups. Results can be paginated, filtered, searched, and sorted. — operationId: getAccountGroupsPage */
	"GET /account-groups": {
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<AccountGroup>;
	};
	/** Creates a new account group — operationId: postAccountGroup */
	"POST /account-groups": {
		body: AccountGroup;
		response: AccountGroup;
	};
	/** Assigns an account by its external reference code to an account group by external reference code — operationId: postAccountGroupByExternalReferenceCodeAccountByExternalReferenceCode */
	"POST /account-groups/by-external-reference-code/{accountExternalReferenceCode}/accounts/by-external-reference-code/{externalReferenceCode}": {
		params: {
			accountExternalReferenceCode: string;
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Removes an account by their external reference code from an account group by external reference code — operationId: deleteAccountGroupByExternalReferenceCodeAccountByExternalReferenceCode */
	"DELETE /account-groups/by-external-reference-code/{accountExternalReferenceCode}/accounts/by-external-reference-code/{externalReferenceCode}": {
		params: {
			accountExternalReferenceCode: string;
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Retrieves the list of accounts in an account group. — operationId: getAccountGroupByExternalReferenceCodeAccountsPage */
	"GET /account-groups/by-external-reference-code/{accountGroupExternalReferenceCode}/accounts": {
		params: {
			accountGroupExternalReferenceCode: string;
		};
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<Account>;
	};
	/** operationId: getAccountGroupByExternalReferenceCode */
	"GET /account-groups/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: AccountGroup;
	};
	/** Replaces the account group with information sent in the request body. Any missing fields are deleted unless they are required. — operationId: putAccountGroupByExternalReferenceCode */
	"PUT /account-groups/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		body: AccountGroup;
		response: AccountGroup;
	};
	/** Updates the account with information sent in the request body. Only the provided fields are updated. — operationId: patchAccountGroupByExternalReferenceCode */
	"PATCH /account-groups/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		body: AccountGroup;
		response: AccountGroup;
	};
	/** Deletes an account group. — operationId: deleteAccountGroupByExternalReferenceCode */
	"DELETE /account-groups/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: void;
	};
	/** operationId: getAccountGroup */
	"GET /account-groups/{accountGroupId}": {
		params: {
			accountGroupId: number;
		};
		response: AccountGroup;
	};
	/** Replaces the account group with information sent in the request body. Any missing fields are deleted unless they are required. — operationId: putAccountGroup */
	"PUT /account-groups/{accountGroupId}": {
		params: {
			accountGroupId: number;
		};
		body: AccountGroup;
		response: AccountGroup;
	};
	/** Updates the account group with information sent in the request body. Only the provided fields are updated. — operationId: patchAccountGroup */
	"PATCH /account-groups/{accountGroupId}": {
		params: {
			accountGroupId: number;
		};
		body: AccountGroup;
		response: AccountGroup;
	};
	/** Deletes an account group. — operationId: deleteAccountGroup */
	"DELETE /account-groups/{accountGroupId}": {
		params: {
			accountGroupId: number;
		};
		response: void;
	};
	/** Retrieves the list of accounts in an account group. — operationId: getAccountGroupAccountsPage */
	"GET /account-groups/{accountGroupId}/accounts": {
		params: {
			accountGroupId: number;
		};
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<Account>;
	};
	/** Retrieves the accounts. Results can be paginated, filtered, searched, and sorted. — operationId: getAccountsPage */
	"GET /accounts": {
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<Account>;
	};
	/** Creates a new account — operationId: postAccount */
	"POST /accounts": {
		body: Account;
		response: Account;
	};
	"GET /accounts/by-external-reference-code/{accountExternalReferenceCode}/account-groups": {
		params: {
			accountExternalReferenceCode: string;
		};
		query: {
			page?: number;
			pageSize?: number;
		};
		response: Page<AccountGroup>;
	};
	/** Assigns account users by external reference code to the account role — operationId: postAccountByExternalReferenceCodeAccountRoleByExternalReferenceCodeUserAccountByExternalReferenceCode */
	"POST /accounts/by-external-reference-code/{accountExternalReferenceCode}/account-roles/by-external-reference-code/{accountRoleExternalReferenceCode}/user-accounts/by-external-reference-code/{externalReferenceCode}": {
		params: {
			accountExternalReferenceCode: string;
			accountRoleExternalReferenceCode: string;
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Unassigns account users by external reference code from the account role — operationId: deleteAccountByExternalReferenceCodeAccountRoleByExternalReferenceCodeUserAccountByExternalReferenceCode */
	"DELETE /accounts/by-external-reference-code/{accountExternalReferenceCode}/account-roles/by-external-reference-code/{accountRoleExternalReferenceCode}/user-accounts/by-external-reference-code/{externalReferenceCode}": {
		params: {
			accountExternalReferenceCode: string;
			accountRoleExternalReferenceCode: string;
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Assigns account users by external reference code to the account role — operationId: postAccountByExternalReferenceCodeAccountRoleUserAccountByExternalReferenceCode */
	"POST /accounts/by-external-reference-code/{accountExternalReferenceCode}/account-roles/{accountRoleId}/user-accounts/by-external-reference-code/{externalReferenceCode}": {
		params: {
			accountExternalReferenceCode: string;
			accountRoleId: number;
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Unassigns account users by external reference code from the account role — operationId: deleteAccountByExternalReferenceCodeAccountRoleUserAccountByExternalReferenceCode */
	"DELETE /accounts/by-external-reference-code/{accountExternalReferenceCode}/account-roles/{accountRoleId}/user-accounts/by-external-reference-code/{externalReferenceCode}": {
		params: {
			accountExternalReferenceCode: string;
			accountRoleId: number;
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Gets a user by their external reference code to an account by external reference code — operationId: getAccountByExternalReferenceCodeUserAccountByExternalReferenceCode */
	"GET /accounts/by-external-reference-code/{accountExternalReferenceCode}/user-accounts/by-external-reference-code/{externalReferenceCode}": {
		params: {
			accountExternalReferenceCode: string;
			externalReferenceCode: string;
		};
		response: UserAccount;
	};
	/** Assigns a user by their external reference code to an account by external reference code — operationId: postAccountByExternalReferenceCodeUserAccountByExternalReferenceCode */
	"POST /accounts/by-external-reference-code/{accountExternalReferenceCode}/user-accounts/by-external-reference-code/{externalReferenceCode}": {
		params: {
			accountExternalReferenceCode: string;
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Removes a user by their external reference code from an account by external reference code — operationId: deleteAccountByExternalReferenceCodeUserAccountByExternalReferenceCode */
	"DELETE /accounts/by-external-reference-code/{accountExternalReferenceCode}/user-accounts/by-external-reference-code/{externalReferenceCode}": {
		params: {
			accountExternalReferenceCode: string;
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Gets a user's account roles by their external reference code from an account by external reference code — operationId: getAccountByExternalReferenceCodeUserAccountByExternalReferenceCodeAccountRolesPage */
	"GET /accounts/by-external-reference-code/{accountExternalReferenceCode}/user-accounts/by-external-reference-code/{externalReferenceCode}/account-roles": {
		params: {
			accountExternalReferenceCode: string;
			externalReferenceCode: string;
		};
		response: Page<AccountRole>;
	};
	/** operationId: getAccountByExternalReferenceCode */
	"GET /accounts/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: Account;
	};
	/** Replaces the account with information sent in the request body. Any missing fields are deleted unless they are required. — operationId: putAccountByExternalReferenceCode */
	"PUT /accounts/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		body: Account;
		response: Account;
	};
	/** Updates the account with information sent in the request body. Only the provided fields are updated. — operationId: patchAccountByExternalReferenceCode */
	"PATCH /accounts/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		body: Account;
		response: Account;
	};
	/** Deletes an account. — operationId: deleteAccountByExternalReferenceCode */
	"DELETE /accounts/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Gets the account's roles — operationId: getAccountAccountRolesByExternalReferenceCodePage */
	"GET /accounts/by-external-reference-code/{externalReferenceCode}/account-roles": {
		params: {
			externalReferenceCode: string;
		};
		query: {
			filter?: string;
			keywords?: string;
			page?: number;
			pageSize?: number;
			sort?: string;
		};
		response: Page<AccountRole>;
	};
	/** Adds a role for the account — operationId: postAccountAccountRoleByExternalReferenceCode */
	"POST /accounts/by-external-reference-code/{externalReferenceCode}/account-roles": {
		params: {
			externalReferenceCode: string;
		};
		body: AccountRole;
		response: AccountRole;
	};
	/** Assigns account users by email address to the account role — operationId: postAccountByExternalReferenceCodeAccountRoleByExternalReferenceCodeUserAccountByEmailAddress */
	"POST /accounts/by-external-reference-code/{externalReferenceCode}/account-roles/by-external-reference-code/{accountRoleExternalReferenceCode}/user-accounts/by-email-address/{emailAddress}": {
		params: {
			accountRoleExternalReferenceCode: string;
			emailAddress: string;
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Unassigns account users by email address from the account role — operationId: deleteAccountByExternalReferenceCodeAccountRoleByExternalReferenceCodeUserAccountByEmailAddress */
	"DELETE /accounts/by-external-reference-code/{externalReferenceCode}/account-roles/by-external-reference-code/{accountRoleExternalReferenceCode}/user-accounts/by-email-address/{emailAddress}": {
		params: {
			accountRoleExternalReferenceCode: string;
			emailAddress: string;
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Assigns account users by email address to the account role — operationId: postAccountByExternalReferenceCodeAccountRoleUserAccountByEmailAddress */
	"POST /accounts/by-external-reference-code/{externalReferenceCode}/account-roles/{accountRoleId}/user-accounts/by-email-address/{emailAddress}": {
		params: {
			accountRoleId: number;
			emailAddress: string;
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Unassigns account users by email address from the account role — operationId: deleteAccountByExternalReferenceCodeAccountRoleUserAccountByEmailAddress */
	"DELETE /accounts/by-external-reference-code/{externalReferenceCode}/account-roles/{accountRoleId}/user-accounts/by-email-address/{emailAddress}": {
		params: {
			accountRoleId: number;
			emailAddress: string;
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Retrieves the account's email addresses. — operationId: getAccountByExternalReferenceCodeEmailAddressesPage */
	"GET /accounts/by-external-reference-code/{externalReferenceCode}/email-addresses": {
		params: {
			externalReferenceCode: string;
		};
		response: Page<EmailAddress>;
	};
	/** Retrieves the account's organizations. Results can be paginated, filtered, searched, and sorted. */
	"GET /accounts/by-external-reference-code/{externalReferenceCode}/organizations": {
		params: {
			externalReferenceCode: string;
		};
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<Organization>;
	};
	"GET /accounts/by-external-reference-code/{externalReferenceCode}/organizations/{organizationId}": {
		params: {
			externalReferenceCode: string;
			organizationId: string;
		};
		response: Organization;
	};
	"POST /accounts/by-external-reference-code/{externalReferenceCode}/organizations/{organizationId}": {
		params: {
			externalReferenceCode: string;
			organizationId: string;
		};
		response: void;
	};
	"DELETE /accounts/by-external-reference-code/{externalReferenceCode}/organizations/{organizationId}": {
		params: {
			externalReferenceCode: string;
			organizationId: string;
		};
		response: void;
	};
	/** Retrieves the account's phone numbers. — operationId: getAccountByExternalReferenceCodePhonesPage */
	"GET /accounts/by-external-reference-code/{externalReferenceCode}/phones": {
		params: {
			externalReferenceCode: string;
		};
		response: Page<Phone>;
	};
	/** Retrieves the account's postal addresses. — operationId: getAccountByExternalReferenceCodePostalAddressesPage */
	"GET /accounts/by-external-reference-code/{externalReferenceCode}/postal-addresses": {
		params: {
			externalReferenceCode: string;
		};
		response: Page<PostalAddress>;
	};
	/** Gets the users assigned to an account — operationId: getAccountUserAccountsByExternalReferenceCodePage */
	"GET /accounts/by-external-reference-code/{externalReferenceCode}/user-accounts": {
		params: {
			externalReferenceCode: string;
		};
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<UserAccount>;
	};
	/** Creates a user and assigns them to the account — operationId: postAccountUserAccountByExternalReferenceCode */
	"POST /accounts/by-external-reference-code/{externalReferenceCode}/user-accounts": {
		params: {
			externalReferenceCode: string;
		};
		body: UserAccount;
		response: UserAccount;
	};
	/** Assigns users to an account by their email addresses — operationId: postAccountUserAccountsByExternalReferenceCodeByEmailAddress */
	"POST /accounts/by-external-reference-code/{externalReferenceCode}/user-accounts/by-email-address": {
		params: {
			externalReferenceCode: string;
		};
		query: {
			accountRoleIds?: string;
		};
		body: string[];
		response: Page<UserAccount>;
	};
	/** Removes users from an account by their email addresses — operationId: deleteAccountUserAccountsByExternalReferenceCodeByEmailAddress */
	"DELETE /accounts/by-external-reference-code/{externalReferenceCode}/user-accounts/by-email-address": {
		params: {
			externalReferenceCode: string;
		};
		body: string[];
		response: void;
	};
	/** Assigns a user to an account by external reference code by their email address — operationId: postAccountUserAccountByExternalReferenceCodeByEmailAddress */
	"POST /accounts/by-external-reference-code/{externalReferenceCode}/user-accounts/by-email-address/{emailAddress}": {
		params: {
			emailAddress: string;
			externalReferenceCode: string;
		};
		response: UserAccount;
	};
	/** Removes a user from an account by external reference code by their email address — operationId: deleteAccountUserAccountByExternalReferenceCodeByEmailAddress */
	"DELETE /accounts/by-external-reference-code/{externalReferenceCode}/user-accounts/by-email-address/{emailAddress}": {
		params: {
			emailAddress: string;
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Gets a user's account roles by their email address from an account by external reference code — operationId: getAccountByExternalReferenceCodeUserAccountByEmailAddressAccountRolesPage */
	"GET /accounts/by-external-reference-code/{externalReferenceCode}/user-accounts/by-email-address/{emailAddress}/account-roles": {
		params: {
			emailAddress: string;
			externalReferenceCode: string;
		};
		response: Page<AccountRole>;
	};
	/** Retrieves the account's web URLs. — operationId: getAccountByExternalReferenceCodeWebUrlsPage */
	"GET /accounts/by-external-reference-code/{externalReferenceCode}/web-urls": {
		params: {
			externalReferenceCode: string;
		};
		response: Page<WebUrl>;
	};
	/** operationId: getAccount */
	"GET /accounts/{accountId}": {
		params: {
			accountId: number;
		};
		response: Account;
	};
	/** Replaces the account with information sent in the request body. Any missing fields are deleted unless they are required. — operationId: putAccount */
	"PUT /accounts/{accountId}": {
		params: {
			accountId: number;
		};
		body: Account;
		response: Account;
	};
	/** Updates the account with information sent in the request body. Only the provided fields are updated. — operationId: patchAccount */
	"PATCH /accounts/{accountId}": {
		params: {
			accountId: number;
		};
		body: Account;
		response: Account;
	};
	/** Deletes an account. — operationId: deleteAccount */
	"DELETE /accounts/{accountId}": {
		params: {
			accountId: number;
		};
		response: void;
	};
	"GET /accounts/{accountId}/account-groups": {
		params: {
			accountId: number;
		};
		query: {
			page?: number;
			pageSize?: number;
		};
		response: Page<AccountGroup>;
	};
	/** Gets the account's roles — operationId: getAccountAccountRolesPage */
	"GET /accounts/{accountId}/account-roles": {
		params: {
			accountId: number;
		};
		query: {
			filter?: string;
			keywords?: string;
			page?: number;
			pageSize?: number;
			sort?: string;
		};
		response: Page<AccountRole>;
	};
	/** Adds a role for the account — operationId: postAccountAccountRole */
	"POST /accounts/{accountId}/account-roles": {
		params: {
			accountId: number;
		};
		body: AccountRole;
		response: AccountRole;
	};
	/** Assigns account users to the account role — operationId: postAccountAccountRoleUserAccountAssociation */
	"POST /accounts/{accountId}/account-roles/{accountRoleId}/user-accounts/{userAccountId}": {
		params: {
			accountId: number;
			accountRoleId: number;
			userAccountId: number;
		};
		response: void;
	};
	/** Unassigns account users to the account role — operationId: deleteAccountAccountRoleUserAccountAssociation */
	"DELETE /accounts/{accountId}/account-roles/{accountRoleId}/user-accounts/{userAccountId}": {
		params: {
			accountId: number;
			accountRoleId: number;
			userAccountId: number;
		};
		response: void;
	};
	/** Retrieves the account's email addresses. — operationId: getAccountEmailAddressesPage */
	"GET /accounts/{accountId}/email-addresses": {
		params: {
			accountId: number;
		};
		response: Page<EmailAddress>;
	};
	/** Retrieves the account's organizations. Results can be paginated, filtered, searched, and sorted. */
	"GET /accounts/{accountId}/organizations": {
		params: {
			accountId: number;
		};
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<Organization>;
	};
	"GET /accounts/{accountId}/organizations/{organizationId}": {
		params: {
			accountId: number;
			organizationId: string;
		};
		response: Organization;
	};
	"POST /accounts/{accountId}/organizations/{organizationId}": {
		params: {
			accountId: number;
			organizationId: string;
		};
		response: void;
	};
	"DELETE /accounts/{accountId}/organizations/{organizationId}": {
		params: {
			accountId: number;
			organizationId: string;
		};
		response: void;
	};
	/** Retrieves the account's phone numbers. — operationId: getAccountPhonesPage */
	"GET /accounts/{accountId}/phones": {
		params: {
			accountId: number;
		};
		response: Page<Phone>;
	};
	/** Retrieves the account's postal addresses. — operationId: getAccountPostalAddressesPage */
	"GET /accounts/{accountId}/postal-addresses": {
		params: {
			accountId: number;
		};
		response: Page<PostalAddress>;
	};
	/** operationId: postAccountPostalAddress */
	"POST /accounts/{accountId}/postal-addresses": {
		params: {
			accountId: number;
		};
		body: PostalAddress;
		response: PostalAddress;
	};
	/** Gets the users assigned to an account — operationId: getAccountUserAccountsPage */
	"GET /accounts/{accountId}/user-accounts": {
		params: {
			accountId: number;
		};
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<UserAccount>;
	};
	/** Creates a user and assigns them to the account — operationId: postAccountUserAccount */
	"POST /accounts/{accountId}/user-accounts": {
		params: {
			accountId: number;
		};
		body: UserAccount;
		response: UserAccount;
	};
	/** Assigns users to an account by their email addresses — operationId: postAccountUserAccountsByEmailAddress */
	"POST /accounts/{accountId}/user-accounts/by-email-address": {
		params: {
			accountId: number;
		};
		query: {
			accountRoleIds?: string;
		};
		body: string[];
		response: Page<UserAccount>;
	};
	/** Removes users from an account by their email addresses — operationId: deleteAccountUserAccountsByEmailAddress */
	"DELETE /accounts/{accountId}/user-accounts/by-email-address": {
		params: {
			accountId: number;
		};
		body: string[];
		response: void;
	};
	/** Assigns a user to an account by their email address — operationId: postAccountUserAccountByEmailAddress */
	"POST /accounts/{accountId}/user-accounts/by-email-address/{emailAddress}": {
		params: {
			accountId: number;
			emailAddress: string;
		};
		response: UserAccount;
	};
	/** Removes a user from an account by their email address — operationId: deleteAccountUserAccountByEmailAddress */
	"DELETE /accounts/{accountId}/user-accounts/by-email-address/{emailAddress}": {
		params: {
			accountId: number;
			emailAddress: string;
		};
		response: void;
	};
	/** Gets a user assigned to an account — operationId: getAccountUserAccount */
	"GET /accounts/{accountId}/user-accounts/{userAccountId}": {
		params: {
			accountId: number;
			userAccountId: number;
		};
		response: UserAccount;
	};
	/** Removes a user assigned to an account — operationId: deleteAccountUserAccount */
	"DELETE /accounts/{accountId}/user-accounts/{userAccountId}": {
		params: {
			accountId: number;
			userAccountId: number;
		};
		response: void;
	};
	/** Retrieves the account's web URLs. — operationId: getAccountWebUrlsPage */
	"GET /accounts/{accountId}/web-urls": {
		params: {
			accountId: number;
		};
		response: Page<WebUrl>;
	};
	/** Retrieves the email address. — operationId: getEmailAddressByExternalReferenceCode */
	"GET /email-addresses/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: EmailAddress;
	};
	/** Updates the email address with the information sent in the request body. Fields not present in the request body are left unchanged. — operationId: patchEmailAddressByExternalReferenceCode */
	"PATCH /email-addresses/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		body: EmailAddress;
		response: EmailAddress;
	};
	/** Deletes an email address. — operationId: deleteEmailAddressByExternalReferenceCode */
	"DELETE /email-addresses/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Retrieves the email address. — operationId: getEmailAddress */
	"GET /email-addresses/{emailAddressId}": {
		params: {
			emailAddressId: number;
		};
		response: EmailAddress;
	};
	/** Updates the email address with the information sent in the request body. Fields not present in the request body are left unchanged. — operationId: patchEmailAddress */
	"PATCH /email-addresses/{emailAddressId}": {
		params: {
			emailAddressId: number;
		};
		body: EmailAddress;
		response: EmailAddress;
	};
	/** Deletes an email address. — operationId: deleteEmailAddress */
	"DELETE /email-addresses/{emailAddressId}": {
		params: {
			emailAddressId: number;
		};
		response: void;
	};
	/** Retrieves information about the user who made the request. — operationId: getMyUserAccount */
	"GET /my-user-account": {
		response: UserAccount;
	};
	/** operationId: getMyUserAccountSharedAssetsSharedByMePage */
	"GET /my-user-account/shared-assets/shared-by-me": {
		query: {
			aggregationTerms?: string[];
			filter?: string;
			nestedFields?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<SharedAsset>;
	};
	/** operationId: getMyUserAccountSharedAssetsSharedWithMePage */
	"GET /my-user-account/shared-assets/shared-with-me": {
		query: {
			aggregationTerms?: string[];
			filter?: string;
			nestedFields?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<SharedAsset>;
	};
	/** operationId: getMyUserAccountSitesPage */
	"GET /my-user-account/sites": {
		query: {
			page?: number;
			pageSize?: number;
		};
		response: Page<Site>;
	};
	/** operationId: getMyUserAccountSubscriptionsPage */
	"GET /my-user-account/subscriptions": {
		query: {
			contentType?: string;
			page?: number;
			pageSize?: number;
		};
		response: Page<Subscription>;
	};
	/** operationId: getMyUserAccountSubscription */
	"GET /my-user-account/subscriptions/{subscriptionId}": {
		params: {
			subscriptionId: number;
		};
		response: Subscription;
	};
	/** operationId: deleteMyUserAccountSubscription */
	"DELETE /my-user-account/subscriptions/{subscriptionId}": {
		params: {
			subscriptionId: number;
		};
		response: void;
	};
	/** Retrieves the organizations. Results can be paginated, filtered, searched, and sorted. — operationId: getOrganizationsPage */
	"GET /organizations": {
		query: {
			filter?: string;
			flatten?: boolean;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<Organization>;
	};
	/** Creates a new organization — operationId: postOrganization */
	"POST /organizations": {
		body: Organization;
		response: Organization;
	};
	"GET /organizations/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: Organization;
	};
	/** Replaces the organization with information sent in the request body. Any missing fields are deleted unless they are required. */
	"PUT /organizations/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		body: Organization;
		response: Organization;
	};
	/** Updates the organization with information sent in the request body. Only the provided fields are updated. */
	"PATCH /organizations/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		body: Organization;
		response: Organization;
	};
	/** Deletes an organization. */
	"DELETE /organizations/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Retrieves the organization's members (accounts). Results can be paginated, filtered, searched, and sorted. — operationId: getOrganizationByExternalReferenceCodeAccountsPage */
	"GET /organizations/by-external-reference-code/{externalReferenceCode}/accounts": {
		params: {
			externalReferenceCode: string;
		};
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<Account>;
	};
	/** operationId: postOrganizationByExternalReferenceCodeAccounts */
	"POST /organizations/by-external-reference-code/{externalReferenceCode}/accounts": {
		params: {
			externalReferenceCode: string;
		};
		body: number[];
		response: void;
	};
	/** operationId: deleteOrganizationByExternalReferenceCodeAccounts */
	"DELETE /organizations/by-external-reference-code/{externalReferenceCode}/accounts": {
		params: {
			externalReferenceCode: string;
		};
		body: number[];
		response: void;
	};
	/** Retrieves the parent organization's child organizations. Results can be paginated, filtered, searched, and sorted. — operationId: getOrganizationByExternalReferenceCodeChildOrganizationsPage */
	"GET /organizations/by-external-reference-code/{externalReferenceCode}/child-organizations": {
		params: {
			externalReferenceCode: string;
		};
		query: {
			filter?: string;
			flatten?: boolean;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<Organization>;
	};
	/** Retrieves the organization's email addresses. — operationId: getOrganizationByExternalReferenceCodeEmailAddressesPage */
	"GET /organizations/by-external-reference-code/{externalReferenceCode}/email-addresses": {
		params: {
			externalReferenceCode: string;
		};
		response: Page<EmailAddress>;
	};
	/** Retrieves the organization's phone numbers. — operationId: getOrganizationByExternalReferenceCodePhonesPage */
	"GET /organizations/by-external-reference-code/{externalReferenceCode}/phones": {
		params: {
			externalReferenceCode: string;
		};
		response: Page<Phone>;
	};
	/** Retrieves the organization's postal addresses. — operationId: getOrganizationByExternalReferenceCodePostalAddressesPage */
	"GET /organizations/by-external-reference-code/{externalReferenceCode}/postal-addresses": {
		params: {
			externalReferenceCode: string;
		};
		response: Page<PostalAddress>;
	};
	/** Retrieves the organization's members (users). Results can be paginated, filtered, searched, and sorted. — operationId: getOrganizationByExternalReferenceCodeUserAccountsPage */
	"GET /organizations/by-external-reference-code/{externalReferenceCode}/user-accounts": {
		params: {
			externalReferenceCode: string;
		};
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<UserAccount>;
	};
	/** Assigns users to an organization by their email addresses — operationId: postOrganizationByExternalReferenceCodeUserAccountsByEmailAddress */
	"POST /organizations/by-external-reference-code/{externalReferenceCode}/user-accounts/by-email-address": {
		params: {
			externalReferenceCode: string;
		};
		query: {
			organizationRoleIds?: string;
		};
		body: string[];
		response: Page<UserAccount>;
	};
	/** Removes users from an organization by their email addresses — operationId: deleteOrganizationByExternalReferenceCodeUserAccountsByEmailAddress */
	"DELETE /organizations/by-external-reference-code/{externalReferenceCode}/user-accounts/by-email-address": {
		params: {
			externalReferenceCode: string;
		};
		body: string[];
		response: void;
	};
	/** Assigns a user to an organization by their email address — operationId: postOrganizationByExternalReferenceCodeUserAccountByEmailAddress */
	"POST /organizations/by-external-reference-code/{externalReferenceCode}/user-accounts/by-email-address/{emailAddress}": {
		params: {
			emailAddress: string;
			externalReferenceCode: string;
		};
		response: UserAccount;
	};
	/** Removes a user from an organization by their email address — operationId: deleteOrganizationByExternalReferenceCodeUserAccountByEmailAddress */
	"DELETE /organizations/by-external-reference-code/{externalReferenceCode}/user-accounts/by-email-address/{emailAddress}": {
		params: {
			emailAddress: string;
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Retrieves the organization's web URLs. — operationId: getOrganizationByExternalReferenceCodeWebUrlsPage */
	"GET /organizations/by-external-reference-code/{externalReferenceCode}/web-urls": {
		params: {
			externalReferenceCode: string;
		};
		response: Page<WebUrl>;
	};
	/** Retrieves the organization's members (accounts) by external reference code. Results can be paginated, filtered, searched, and sorted. */
	"GET /organizations/by-external-reference-code/{organizationExternalReferenceCode}/accounts/by-external-reference-code": {
		params: {
			organizationExternalReferenceCode: string;
		};
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<Account>;
	};
	"POST /organizations/by-external-reference-code/{organizationExternalReferenceCode}/accounts/by-external-reference-code": {
		params: {
			organizationExternalReferenceCode: string;
		};
		body: string[];
		response: void;
	};
	"DELETE /organizations/by-external-reference-code/{organizationExternalReferenceCode}/accounts/by-external-reference-code": {
		params: {
			organizationExternalReferenceCode: string;
		};
		body: string[];
		response: void;
	};
	/** operationId: patchOrganizationMoveAccounts */
	"PATCH /organizations/move-accounts/{sourceOrganizationId}/{targetOrganizationId}": {
		params: {
			sourceOrganizationId: number;
			targetOrganizationId: number;
		};
		body: number[];
		response: void;
	};
	/** operationId: patchOrganizationMoveAccountsByExternalReferenceCode */
	"PATCH /organizations/move-accounts/{sourceOrganizationId}/{targetOrganizationId}/by-external-reference-code": {
		params: {
			sourceOrganizationId: number;
			targetOrganizationId: number;
		};
		body: string[];
		response: void;
	};
	/** Retrieves the organization. — operationId: getOrganization */
	"GET /organizations/{organizationId}": {
		params: {
			organizationId: string;
		};
		response: Organization;
	};
	/** Replaces the organization with information sent in the request body. Any missing fields are deleted unless they are required. — operationId: putOrganization */
	"PUT /organizations/{organizationId}": {
		params: {
			organizationId: string;
		};
		body: Organization;
		response: Organization;
	};
	/** Updates the organization with the information sent in the request body. Fields not present in the request body are left unchanged. — operationId: patchOrganization */
	"PATCH /organizations/{organizationId}": {
		params: {
			organizationId: string;
		};
		body: Organization;
		response: Organization;
	};
	/** Deletes an organization. — operationId: deleteOrganization */
	"DELETE /organizations/{organizationId}": {
		params: {
			organizationId: string;
		};
		response: void;
	};
	/** Retrieves the organization's members (accounts). Results can be paginated, filtered, searched, and sorted. — operationId: getOrganizationAccountsPage */
	"GET /organizations/{organizationId}/accounts": {
		params: {
			organizationId: string;
		};
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<Account>;
	};
	/** operationId: postOrganizationAccounts */
	"POST /organizations/{organizationId}/accounts": {
		params: {
			organizationId: number;
		};
		body: number[];
		response: void;
	};
	/** operationId: deleteOrganizationAccounts */
	"DELETE /organizations/{organizationId}/accounts": {
		params: {
			organizationId: number;
		};
		body: number[];
		response: void;
	};
	/** operationId: postOrganizationAccountsByExternalReferenceCode */
	"POST /organizations/{organizationId}/accounts/by-external-reference-code": {
		params: {
			organizationId: number;
		};
		body: string[];
		response: void;
	};
	/** operationId: deleteOrganizationAccountsByExternalReferenceCode */
	"DELETE /organizations/{organizationId}/accounts/by-external-reference-code": {
		params: {
			organizationId: number;
		};
		body: string[];
		response: void;
	};
	/** Retrieves the parent organization's child organizations. Results can be paginated, filtered, searched, and sorted. — operationId: getOrganizationChildOrganizationsPage */
	"GET /organizations/{organizationId}/child-organizations": {
		params: {
			organizationId: string;
		};
		query: {
			filter?: string;
			flatten?: boolean;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<Organization>;
	};
	/** Retrieves the organization's email addresses. — operationId: getOrganizationEmailAddressesPage */
	"GET /organizations/{organizationId}/email-addresses": {
		params: {
			organizationId: string;
		};
		response: Page<EmailAddress>;
	};
	/** Retrieves the organization's phone numbers. — operationId: getOrganizationPhonesPage */
	"GET /organizations/{organizationId}/phones": {
		params: {
			organizationId: string;
		};
		response: Page<Phone>;
	};
	/** Retrieves the organization's postal addresses. — operationId: getOrganizationPostalAddressesPage */
	"GET /organizations/{organizationId}/postal-addresses": {
		params: {
			organizationId: string;
		};
		response: Page<PostalAddress>;
	};
	/** Retrieves the organization's members (users). Results can be paginated, filtered, searched, and sorted. — operationId: getOrganizationUserAccountsPage */
	"GET /organizations/{organizationId}/user-accounts": {
		params: {
			organizationId: string;
		};
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<UserAccount>;
	};
	/** Assigns users to an organization by their email addresses — operationId: postUserAccountsByEmailAddress */
	"POST /organizations/{organizationId}/user-accounts/by-email-address": {
		params: {
			organizationId: string;
		};
		query: {
			organizationRoleIds?: string;
		};
		body: string[];
		response: Page<UserAccount>;
	};
	/** Removes users from an organization by their email addresses — operationId: deleteUserAccountsByEmailAddress */
	"DELETE /organizations/{organizationId}/user-accounts/by-email-address": {
		params: {
			organizationId: string;
		};
		body: string[];
		response: void;
	};
	/** Assigns a user to an organization by their email address — operationId: postUserAccountByEmailAddress */
	"POST /organizations/{organizationId}/user-accounts/by-email-address/{emailAddress}": {
		params: {
			emailAddress: string;
			organizationId: string;
		};
		response: UserAccount;
	};
	/** Removes a user from an organization by their email address — operationId: deleteUserAccountByEmailAddress */
	"DELETE /organizations/{organizationId}/user-accounts/by-email-address/{emailAddress}": {
		params: {
			emailAddress: string;
			organizationId: string;
		};
		response: void;
	};
	/** Retrieves the organization's URLs. — operationId: getOrganizationWebUrlsPage */
	"GET /organizations/{organizationId}/web-urls": {
		params: {
			organizationId: string;
		};
		response: Page<WebUrl>;
	};
	/** Retrieves the parent organization's child organizations. Results can be paginated, filtered, searched, and sorted. — operationId: getOrganizationOrganizationsPage */
	"GET /organizations/{parentOrganizationId}/organizations": {
		params: {
			parentOrganizationId: string;
		};
		query: {
			filter?: string;
			flatten?: boolean;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<Organization>;
	};
	/** Retrieves the phone number by external reference code. — operationId: getPhoneByExternalReferenceCode */
	"GET /phones/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: Phone;
	};
	/** Updates the phone number by external reference code. — operationId: patchPhoneByExternalReferenceCode */
	"PATCH /phones/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		body: Phone;
		response: Phone;
	};
	/** Deletes the phone number by external reference code. — operationId: deletePhoneByExternalReferenceCode */
	"DELETE /phones/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Retrieves the phone number. — operationId: getPhone */
	"GET /phones/{phoneId}": {
		params: {
			phoneId: number;
		};
		response: Phone;
	};
	/** Updates the phone number. — operationId: patchPhone */
	"PATCH /phones/{phoneId}": {
		params: {
			phoneId: number;
		};
		body: Phone;
		response: Phone;
	};
	/** Deletes the phone number. — operationId: deletePhone */
	"DELETE /phones/{phoneId}": {
		params: {
			phoneId: number;
		};
		response: void;
	};
	/** Retrieves the postal address using external reference code. — operationId: getPostalAddressByExternalReferenceCode */
	"GET /postal-addresses/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: PostalAddress;
	};
	/** Updates the postal address using external reference code. — operationId: putPostalAddressByExternalReferenceCode */
	"PUT /postal-addresses/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		body: PostalAddress;
		response: PostalAddress;
	};
	/** Updates the postal address using external reference code. — operationId: patchPostalAddressByExternalReferenceCode */
	"PATCH /postal-addresses/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		body: PostalAddress;
		response: PostalAddress;
	};
	/** Deletes the postal address using external reference code. — operationId: deletePostalAddressByExternalReferenceCode */
	"DELETE /postal-addresses/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Retrieves the postal address. — operationId: getPostalAddress */
	"GET /postal-addresses/{postalAddressId}": {
		params: {
			postalAddressId: number;
		};
		response: PostalAddress;
	};
	/** operationId: putPostalAddress */
	"PUT /postal-addresses/{postalAddressId}": {
		params: {
			postalAddressId: number;
		};
		body: PostalAddress;
		response: PostalAddress;
	};
	/** operationId: patchPostalAddress */
	"PATCH /postal-addresses/{postalAddressId}": {
		params: {
			postalAddressId: number;
		};
		body: PostalAddress;
		response: PostalAddress;
	};
	/** Deletes the postal address — operationId: deletePostalAddress */
	"DELETE /postal-addresses/{postalAddressId}": {
		params: {
			postalAddressId: number;
		};
		response: void;
	};
	/** Retrieves the portal instance's roles. Results can be paginated. — operationId: getRolesPage */
	"GET /roles": {
		query: {
			fields?: string;
			filter?: string;
			page?: number;
			pageSize?: number;
			restrictFields?: string;
			search?: string;
			types?: string[];
		};
		response: Page<Role>;
	};
	/** Creates a new role — operationId: postRole */
	"POST /roles": {
		body: Role;
		response: Role;
	};
	/** Retrieves the role by its external reference code. — operationId: getRoleByExternalReferenceCode */
	"GET /roles/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: Role;
	};
	/** Updates the role by its external reference code. — operationId: putRoleByExternalReferenceCode */
	"PUT /roles/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		body: Role;
		response: Role;
	};
	/** Updates the role by its external reference code. — operationId: patchRoleByExternalReferenceCode */
	"PATCH /roles/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		body: Role;
		response: Role;
	};
	/** Deletes the role by its external reference code. — operationId: deleteRoleByExternalReferenceCode */
	"DELETE /roles/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Associates a role by external reference code with a user account — operationId: postRoleByExternalReferenceCodeUserAccountAssociation */
	"POST /roles/by-external-reference-code/{externalReferenceCode}/association/user-account/{userAccountId}": {
		params: {
			externalReferenceCode: string;
			userAccountId: number;
		};
		response: void;
	};
	/** Unassociates a role by external reference code with a user account — operationId: deleteRoleByExternalReferenceCodeUserAccountAssociation */
	"DELETE /roles/by-external-reference-code/{externalReferenceCode}/association/user-account/{userAccountId}": {
		params: {
			externalReferenceCode: string;
			userAccountId: number;
		};
		response: void;
	};
	/** Associates a organization role by external reference code with a user account — operationId: postOrganizationRoleByExternalReferenceCodeUserAccountAssociation */
	"POST /roles/by-external-reference-code/{externalReferenceCode}/association/user-account/{userAccountId}/organization/{organizationId}": {
		params: {
			externalReferenceCode: string;
			organizationId: number;
			userAccountId: number;
		};
		response: void;
	};
	/** Unassociates an organization role by external reference code with a user account — operationId: deleteOrganizationRoleByExternalReferenceCodeUserAccountAssociation */
	"DELETE /roles/by-external-reference-code/{externalReferenceCode}/association/user-account/{userAccountId}/organization/{organizationId}": {
		params: {
			externalReferenceCode: string;
			organizationId: number;
			userAccountId: number;
		};
		response: void;
	};
	/** Associates a site role by external reference code with a user account — operationId: postSiteRoleByExternalReferenceCodeUserAccountAssociation */
	"POST /roles/by-external-reference-code/{externalReferenceCode}/association/user-account/{userAccountId}/site/{siteId}": {
		params: {
			externalReferenceCode: string;
			siteId: number;
			userAccountId: number;
		};
		response: void;
	};
	/** Unassociates a site role by external reference code with a user account — operationId: deleteSiteRoleByExternalReferenceCodeUserAccountAssociation */
	"DELETE /roles/by-external-reference-code/{externalReferenceCode}/association/user-account/{userAccountId}/site/{siteId}": {
		params: {
			externalReferenceCode: string;
			siteId: number;
			userAccountId: number;
		};
		response: void;
	};
	/** Retrieves the role. — operationId: getRole */
	"GET /roles/{roleId}": {
		params: {
			roleId: number;
		};
		response: Role;
	};
	/** Updates the role. — operationId: putRole */
	"PUT /roles/{roleId}": {
		params: {
			roleId: number;
		};
		body: Role;
		response: Role;
	};
	/** Updates the role. — operationId: patchRole */
	"PATCH /roles/{roleId}": {
		params: {
			roleId: number;
		};
		body: Role;
		response: Role;
	};
	/** Deletes the role. — operationId: deleteRole */
	"DELETE /roles/{roleId}": {
		params: {
			roleId: number;
		};
		response: void;
	};
	/** Associates a role with a user account — operationId: postRoleUserAccountAssociation */
	"POST /roles/{roleId}/association/user-account/{userAccountId}": {
		params: {
			roleId: number;
			userAccountId: number;
		};
		response: void;
	};
	/** Unassociates a role with a user account — operationId: deleteRoleUserAccountAssociation */
	"DELETE /roles/{roleId}/association/user-account/{userAccountId}": {
		params: {
			roleId: number;
			userAccountId: number;
		};
		response: void;
	};
	/** Associates a organization role with a user account — operationId: postOrganizationRoleUserAccountAssociation */
	"POST /roles/{roleId}/association/user-account/{userAccountId}/organization/{organizationId}": {
		params: {
			organizationId: number;
			roleId: number;
			userAccountId: number;
		};
		response: void;
	};
	/** Unassociates an organization role with a user account — operationId: deleteOrganizationRoleUserAccountAssociation */
	"DELETE /roles/{roleId}/association/user-account/{userAccountId}/organization/{organizationId}": {
		params: {
			organizationId: number;
			roleId: number;
			userAccountId: number;
		};
		response: void;
	};
	/** Associates a site role with a user account — operationId: postSiteRoleUserAccountAssociation */
	"POST /roles/{roleId}/association/user-account/{userAccountId}/site/{siteId}": {
		params: {
			roleId: number;
			siteId: number;
			userAccountId: number;
		};
		response: void;
	};
	/** Unassociates a site role with a user account — operationId: deleteSiteRoleUserAccountAssociation */
	"DELETE /roles/{roleId}/association/user-account/{userAccountId}/site/{siteId}": {
		params: {
			roleId: number;
			siteId: number;
			userAccountId: number;
		};
		response: void;
	};
	/** Gets a segment's users. — operationId: getSegmentUserAccountsPage */
	"GET /segments/{segmentId}/user-accounts": {
		params: {
			segmentId: number;
		};
		query: {
			page?: number;
			pageSize?: number;
		};
		response: Page<SegmentUser>;
	};
	/** operationId: getSiteByFriendlyUrlPath */
	"GET /sites/by-friendly-url-path/{friendlyUrlPath}": {
		params: {
			friendlyUrlPath: string;
		};
		response: Site;
	};
	/** Gets the selected property of a user assigned to an account for a specific site */
	"GET /sites/by-friendly-url-path/{friendlyUrlPath}/accounts/by-external-reference-code/{accountExternalReferenceCode}/user-accounts/by-external-reference-code/{userAccountExternalReferenceCode}/selected": {
		params: {
			accountExternalReferenceCode: string;
			friendlyUrlPath: string;
			userAccountExternalReferenceCode: string;
		};
		response: boolean;
	};
	/** Updates the selected property of a user assigned to an account for a specific site */
	"PATCH /sites/by-friendly-url-path/{friendlyUrlPath}/accounts/by-external-reference-code/{accountExternalReferenceCode}/user-accounts/by-external-reference-code/{userAccountExternalReferenceCode}/selected": {
		params: {
			accountExternalReferenceCode: string;
			friendlyUrlPath: string;
			userAccountExternalReferenceCode: string;
		};
		response: void;
	};
	/** operationId: getSite */
	"GET /sites/{siteId}": {
		params: {
			siteId: number;
		};
		response: Site;
	};
	/** Gets the selected property of a user assigned to an account for a specific site */
	"GET /sites/{siteId}/accounts/{accountId}/user-accounts/{userAccountId}/selected": {
		params: {
			accountId: number;
			siteId: number;
			userAccountId: number;
		};
		response: boolean;
	};
	/** Updates the selected property of a user assigned to an account for a specific site */
	"PATCH /sites/{siteId}/accounts/{accountId}/user-accounts/{userAccountId}/selected": {
		params: {
			accountId: number;
			siteId: number;
			userAccountId: number;
		};
		response: void;
	};
	/** Gets a site's segments. — operationId: getSiteSegmentsPage */
	"GET /sites/{siteId}/segments": {
		params: {
			siteId: number;
		};
		query: {
			page?: number;
			pageSize?: number;
		};
		response: Page<Segment>;
	};
	/** Retrieves the site members' user accounts. Results can be paginated, filtered, searched, and sorted. — operationId: getSiteUserAccountsPage */
	"GET /sites/{siteId}/user-accounts": {
		params: {
			siteId: number;
		};
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<UserAccount>;
	};
	/** Gets a user's segments. The set of available headers are: Accept-Language (string), Host (string), User-Agent (string), X-Browser (string), X-Cookies (collection string), X-Device-Brand (string), X-Device-Model (string), X-Device-Screen-Resolution-Height (double), X-Device-Screen-Resolution-Width (double), X-Last-Sign-In-Date-Time (date time) and X-Signed-In (boolean). Local date will be always present in the request. — operationId: getSiteUserAccountSegmentsPage */
	"GET /sites/{siteId}/user-accounts/{userAccountId}/segments": {
		params: {
			siteId: number;
			userAccountId: number;
		};
		response: Page<Segment>;
	};
	/** Retrieves the user account full name definition. */
	"GET /user-account-full-name-definition": {
		query: {
			languageId?: string;
		};
		response: UserAccountFullNameDefinition;
	};
	/** Retrieves the user accounts. Results can be paginated, filtered, searched, and sorted. — operationId: getUserAccountsPage */
	"GET /user-accounts": {
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<UserAccount>;
	};
	/** Creates a new user account — operationId: postUserAccount */
	"POST /user-accounts": {
		query: {
			captchaAnswer?: string;
			captchaToken?: string;
		};
		body: UserAccount;
		response: UserAccount;
	};
	/** operationId: getUserAccountByEmailAddress */
	"GET /user-accounts/by-email-address/{emailAddress}": {
		params: {
			emailAddress: string;
		};
		response: UserAccount;
	};
	/** operationId: getUserAccountByExternalReferenceCode */
	"GET /user-accounts/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: UserAccount;
	};
	/** operationId: putUserAccountByExternalReferenceCode */
	"PUT /user-accounts/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		body: UserAccount;
		response: UserAccount;
	};
	/** Updates the user account with information sent in the request body. Only the provided fields are updated. — operationId: patchUserAccountByExternalReferenceCode */
	"PATCH /user-accounts/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		body: UserAccount;
		response: UserAccount;
	};
	/** operationId: deleteUserAccountByExternalReferenceCode */
	"DELETE /user-accounts/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Retrieves the user's email addresses. — operationId: getUserAccountByExternalReferenceCodeEmailAddressesPage */
	"GET /user-accounts/by-external-reference-code/{externalReferenceCode}/email-addresses": {
		params: {
			externalReferenceCode: string;
		};
		response: Page<EmailAddress>;
	};
	/** Retrieves the user's phone numbers. — operationId: getUserAccountByExternalReferenceCodePhonesPage */
	"GET /user-accounts/by-external-reference-code/{externalReferenceCode}/phones": {
		params: {
			externalReferenceCode: string;
		};
		response: Page<Phone>;
	};
	/** Retrieves the user's postal addresses. — operationId: getUserAccountByExternalReferenceCodePostalAddressesPage */
	"GET /user-accounts/by-external-reference-code/{externalReferenceCode}/postal-addresses": {
		params: {
			externalReferenceCode: string;
		};
		response: Page<PostalAddress>;
	};
	/** Retrieves the user's web URLs. — operationId: getUserAccountByExternalReferenceCodeWebUrlsPage */
	"GET /user-accounts/by-external-reference-code/{externalReferenceCode}/web-urls": {
		params: {
			externalReferenceCode: string;
		};
		response: Page<WebUrl>;
	};
	/** operationId: getUserAccountsByStatusPage */
	"GET /user-accounts/by-status/{status}": {
		params: {
			status: string;
		};
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<UserAccount>;
	};
	/** Retrieves the user account. — operationId: getUserAccount */
	"GET /user-accounts/{userAccountId}": {
		params: {
			userAccountId: number;
		};
		response: UserAccount;
	};
	/** Replaces the user account with information sent in the request body. Any missing fields are deleted unless they are required. — operationId: putUserAccount */
	"PUT /user-accounts/{userAccountId}": {
		params: {
			userAccountId: number;
		};
		body: UserAccount;
		response: UserAccount;
	};
	/** Updates the user account with information sent in the request body. Only the provided fields are updated. — operationId: patchUserAccount */
	"PATCH /user-accounts/{userAccountId}": {
		params: {
			userAccountId: number;
		};
		body: UserAccount;
		response: UserAccount;
	};
	/** Deletes the user account — operationId: deleteUserAccount */
	"DELETE /user-accounts/{userAccountId}": {
		params: {
			userAccountId: number;
		};
		response: void;
	};
	/** Retrieves the user's email addresses. — operationId: getUserAccountEmailAddressesPage */
	"GET /user-accounts/{userAccountId}/email-addresses": {
		params: {
			userAccountId: number;
		};
		response: Page<EmailAddress>;
	};
	/** Retrieves the user's email verification ticket. — operationId: getUserAccountEmailVerificationTicket */
	"GET /user-accounts/{userAccountId}/email-verification-ticket": {
		params: {
			userAccountId: number;
		};
		response: Ticket;
	};
	"POST /user-accounts/{userAccountId}/image": {
		params: {
			userAccountId: number;
		};
		body: Image;
		response: void;
	};
	/** Retrieves the user's password reset ticket. — operationId: getUserAccountPasswordResetTicket */
	"GET /user-accounts/{userAccountId}/password-reset-ticket": {
		params: {
			userAccountId: number;
		};
		response: Ticket;
	};
	/** Retrieves the user's phone numbers. — operationId: getUserAccountPhonesPage */
	"GET /user-accounts/{userAccountId}/phones": {
		params: {
			userAccountId: number;
		};
		response: Page<Phone>;
	};
	/** Retrieves the user's postal addresses. — operationId: getUserAccountPostalAddressesPage */
	"GET /user-accounts/{userAccountId}/postal-addresses": {
		params: {
			userAccountId: number;
		};
		response: Page<PostalAddress>;
	};
	/** Retrieves the user's user groups. — operationId: getUserUserGroups */
	"GET /user-accounts/{userAccountId}/user-groups": {
		params: {
			userAccountId: number;
		};
		response: Page<UserGroup>;
	};
	/** Retrieves the user's URLs. — operationId: getUserAccountWebUrlsPage */
	"GET /user-accounts/{userAccountId}/web-urls": {
		params: {
			userAccountId: number;
		};
		response: Page<WebUrl>;
	};
	/** operationId: getUserGroupsPage */
	"GET /user-groups": {
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<UserGroup>;
	};
	/** operationId: postUserGroup */
	"POST /user-groups": {
		body: UserGroup;
		response: UserGroup;
	};
	/** operationId: getUserGroupByExternalReferenceCode */
	"GET /user-groups/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: UserGroup;
	};
	/** operationId: putUserGroupByExternalReferenceCode */
	"PUT /user-groups/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		body: UserGroup;
		response: UserGroup;
	};
	/** operationId: patchUserGroupByExternalReferenceCode */
	"PATCH /user-groups/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		body: UserGroup;
		response: UserGroup;
	};
	/** operationId: deleteUserGroupByExternalReferenceCode */
	"DELETE /user-groups/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Retrieves the list of users in a user group. — operationId: getUserGroupByExternalReferenceCodeUsersPage */
	"GET /user-groups/by-external-reference-code/{externalReferenceCode}/user-group-users": {
		params: {
			externalReferenceCode: string;
		};
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<UserAccount>;
	};
	/** operationId: postUserGroupByExternalReferenceCodeUsers */
	"POST /user-groups/by-external-reference-code/{externalReferenceCode}/user-group-users": {
		params: {
			externalReferenceCode: string;
		};
		body: number[];
		response: void;
	};
	/** operationId: deleteUserGroupByExternalReferenceCodeUsers */
	"DELETE /user-groups/by-external-reference-code/{externalReferenceCode}/user-group-users": {
		params: {
			externalReferenceCode: string;
		};
		body: number[];
		response: void;
	};
	/** operationId: getUserGroup */
	"GET /user-groups/{userGroupId}": {
		params: {
			userGroupId: number;
		};
		response: UserGroup;
	};
	/** operationId: putUserGroup */
	"PUT /user-groups/{userGroupId}": {
		params: {
			userGroupId: number;
		};
		body: UserGroup;
		response: UserGroup;
	};
	/** operationId: patchUserGroup */
	"PATCH /user-groups/{userGroupId}": {
		params: {
			userGroupId: number;
		};
		body: UserGroup;
		response: UserGroup;
	};
	/** operationId: deleteUserGroup */
	"DELETE /user-groups/{userGroupId}": {
		params: {
			userGroupId: number;
		};
		response: void;
	};
	/** Retrieves the list of users in a user group. — operationId: getUserGroupUsersPage */
	"GET /user-groups/{userGroupId}/user-group-users": {
		params: {
			userGroupId: number;
		};
		query: {
			filter?: string;
			page?: number;
			pageSize?: number;
			search?: string;
			sort?: string;
		};
		response: Page<UserAccount>;
	};
	/** operationId: postUserGroupUsers */
	"POST /user-groups/{userGroupId}/user-group-users": {
		params: {
			userGroupId: number;
		};
		body: number[];
		response: void;
	};
	/** operationId: deleteUserGroupUsers */
	"DELETE /user-groups/{userGroupId}/user-group-users": {
		params: {
			userGroupId: number;
		};
		body: number[];
		response: void;
	};
	/** Retrieves the web URL by external reference code. — operationId: getWebUrlByExternalReferenceCode */
	"GET /web-urls/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: WebUrl;
	};
	/** Updates the web URL by external reference code. — operationId: patchWebUrlByExternalReferenceCode */
	"PATCH /web-urls/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		body: WebUrl;
		response: WebUrl;
	};
	/** Deletes the web URL by external reference code. — operationId: deleteWebUrlByExternalReferenceCode */
	"DELETE /web-urls/by-external-reference-code/{externalReferenceCode}": {
		params: {
			externalReferenceCode: string;
		};
		response: void;
	};
	/** Retrieves the web URL. — operationId: getWebUrl */
	"GET /web-urls/{webUrlId}": {
		params: {
			webUrlId: number;
		};
		response: WebUrl;
	};
	/** Updates the web URL. — operationId: patchWebUrl */
	"PATCH /web-urls/{webUrlId}": {
		params: {
			webUrlId: number;
		};
		body: WebUrl;
		response: WebUrl;
	};
	/** Deletes the web URL. — operationId: deleteWebUrl */
	"DELETE /web-urls/{webUrlId}": {
		params: {
			webUrlId: number;
		};
		response: void;
	};
}

export type EndpointKey = keyof Endpoints;
